# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d14a85e83a6dc07355ea24e7726235a1a7fea337bb9fd5689c2e0beb3e7abc46c636068a719ca97d7dc9a5a7a4ef6a4b01718734c0ac7bfc3c46696da35b4ff

test:
  secret_key_base: d430cc98e74d9d552540891034c98b6e4e66b376b7843875426d528c4d0e6ddf776c04d274b88d7b34b63bc1380222950723cf93ec07a848d0871a0b29b81119

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
